// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Session struct {
	ID            int64           `json:"id"`
	ThreadID      int64           `json:"thread_id"`
	SessionID     string          `json:"session_id"`
	StartedAt     sql.NullTime    `json:"started_at"`
	EndedAt       sql.NullTime    `json:"ended_at"`
	Status        sql.NullString  `json:"status"`
	Model         sql.NullString  `json:"model"`
	TotalCostUsd  sql.NullFloat64 `json:"total_cost_usd"`
	InputTokens   sql.NullInt64   `json:"input_tokens"`
	OutputTokens  sql.NullInt64   `json:"output_tokens"`
	DurationMs    sql.NullInt64   `json:"duration_ms"`
	NumTurns      sql.NullInt64   `json:"num_turns"`
	InitialPrompt sql.NullString  `json:"initial_prompt"`
}

type Thread struct {
	ID               int64        `json:"id"`
	ChannelID        string       `json:"channel_id"`
	ThreadTs         string       `json:"thread_ts"`
	WorkingDirectory string       `json:"working_directory"`
	CreatedAt        sql.NullTime `json:"created_at"`
	UpdatedAt        sql.NullTime `json:"updated_at"`
}

type Worktree struct {
	ID             int64          `json:"id"`
	RepositoryPath string         `json:"repository_path"`
	RepositoryName string         `json:"repository_name"`
	ThreadID       int64          `json:"thread_id"`
	Path           string         `json:"path"`
	BaseBranch     string         `json:"base_branch"`
	CurrentBranch  sql.NullString `json:"current_branch"`
	Status         string         `json:"status"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
}
