// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: repositories.sql

package db

// This file is intentionally empty
// Repository management has been moved to config.yaml
